config/routes.rb
Colombianart2::Application.routes.draw do
  resources :products

  root to: "welcome#index"

  devise_for :users

end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  data       :string(255)
#  product_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Photo < ActiveRecord::Base
  belongs_to :product
  attr_accessible :data
  mount_uploader :data, GravatarUploader
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  user_id     :integer
#  image       :string(255)
#  public      :boolean
#  units       :integer
#  price       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ActiveRecord::Base
  attr_accessible :description, :image, :public, :title, :units, :price

  validates_presence_of :description, :image, :title, :units, :price
  mount_uploader :image, GravatarUploader
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  artisan                :boolean          not null
#  fname                  :string(255)
#  lname                  :string(255)
#  address                :string(255)
#  phone                  :string(255)
#  gravatar               :string(255)
#  gender                 :string(255)
#  description            :string(255)
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :fname, :lname, :gravatar, :artisan
  mount_uploader :gravatar, GravatarUploader
  validates_presence_of :email, :password, :password_confirmation, :fname, :lname, :gravatar

  has_many :products
  
  def full_name
    "#{fname} #{lname}"
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!, only: [:show, :create, :destroy]
  def index
    @products = current_user.products.all
  end

  def show
    @product = Product.find params[:id]
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product])
    @product.user = current_user
    if @product.save
      redirect_to products_path, :notice => "Product successfully added"
    else
      render action: "new", alert: "Errors ocurred while saving"
    end 
  end

  def edit
  end

  def update
  end

  def destroy
    @product = Product.find params[:id]
    if @product.destroy
      redirect_to products_path, :notice => "Product successfully deleted"
    else
      render action: "index", alert: "Errors ocurred while deleting"
    end 
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @products = Product.limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title iArts
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container{:style => "margin-bottom: 300px"}
      .row.clearfix
        .col-md-12.column
          %nav.navbar.navbar-default{:role => "navigation"}
            .navbar-header
              %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
                %span.sr-only Toggle navigation
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
              %a.navbar-brand{:href => "/"} iArts
            #bs-example-navbar-collapse-1.collapse.navbar-collapse
              %ul.nav.navbar-nav
                - if user_signed_in? && current_user.artisan?
                  %li
                    = link_to "My Products", products_path
              %ul.nav.navbar-nav.navbar-right
                - if user_signed_in?
                  %li
                    = link_to root_path do
                      %img.img-circle{:src => current_user.gravatar_url, :width => "20px", :height => "20px"} 
                      = current_user.full_name
                  %li
                    = link_to "Log Out", destroy_user_session_path, :method => :delete
                - else
                  %li
                    = link_to "Sign In", new_user_session_path
                  %li
                    = link_to "Sign Up", new_user_registration_path
        - if notice
          %p.alert.alert-success= notice
        - if alert
          %p.alert= alert
        = yield
    .navbar.navbar-default.navbar-fixed-bottom
      .container
        %p.navbar-text.pull-left Copyright iArts.co
        %a.navbar-btn.btn-danger.btn.pull-right{:href => "http://twitter.com/iartsinc"} Follow on Twitter

  = yield :javascript

app/views/products/_photo.html.haml
%fieldset
  - if !f.object.new_record?
    = image_tag f.object.data_url
  = f.file_field :data
  = delete_photo(f)

app/views/products/create.html.haml
%h1 Products#create
%p Find me in app/views/products/create.html.haml

app/views/products/destroy.html.haml
%h1 Products#destroy
%p Find me in app/views/products/destroy.html.haml

app/views/products/edit.html.haml
%h1 Products#edit
%p Find me in app/views/products/edit.html.haml

app/views/products/index.html.haml
.col-md-12.column
  .well
    = link_to "+ Add Product", new_product_path, :class => "btn btn-primary btn-sm"
  .row
    - @products.each do |product|
      .col-md-4
        .thumbnail
          %img{:alt => "300x200", :src => product.image_url}/
          .caption
            %h3
              = product.title
            %p
              = raw(product.description.truncate(200, :omission => "...#{link_to "show more", '#'}"))
            %p
              %h4 
                %span.label.label-primary= number_to_currency(product.price, :unit => "$")
                %span.label.label-info= "#{product.units} Avl Units"
                = link_to "Show", product_path(product), :class => "btn btn-primary btn-xs"
                = link_to "Delete", product_path(product), :confirm => "Are you sure?", :method=>:delete, :class => "btn btn-danger btn-xs"

app/views/products/new.html.haml
.row  
  .col-md-7{:style => "margin-left: 15px"}
    %legend New Product
    = form_for(@product, :html => {:class => "form-horizontal", :multipart => true}) do |f|
      .form-group
        = f.label :title, :class => "col-sm-2 control-label"
        .col-sm-10
          = f.text_field :title, :autofocus => true, :class => "form-control", :placeholder => "Title"
      .form-group
        = f.label :description, :class => "col-sm-2 control-label"
        .col-sm-10
          = f.text_area :description, :class => "form-control", :placeholder => "Description", :rows => 5
      .form-group
        = f.label "Units Available", :class => "col-sm-2 control-label"
        .col-sm-10
          = f.number_field :units, :class => "form-control", :min => 0
      .form-group
        = f.label "Price in USD", :class => "col-sm-2 control-label"
        .col-sm-10
          = f.number_field :price, :class => "form-control", :min => 0
      .form-group
        %label.col-sm-2.control-label Main Picture
        .col-sm-10
          = f.file_field :image, :id => "imgInp"

      .form-group
        .col-sm-offset-2.col-sm-10
          %button.btn.btn-primary{:type => "submit"} Create Product
  .col-md-3
    %legend Main Picture
    %img{:id => "blah", :class => "img-thumbnail", :src => "http://www.postmyarticle.net/articles/uploads/image_placeholder.jpg"}
- content_for :javascript do
  :javascript
    function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
              $('#blah').attr('src', e.target.result);
          }

          reader.readAsDataURL(input.files[0]);
      }
    }

    $(document).ready(function() {
      $("#imgInp").change(function(){
          readURL(this);
      });
    });

app/views/products/show.html.haml
.row{:style => "margin-left: 15px"}
  .col-md-6
    %legend Main Picture
    %img{:id => "blah", :class => "img-thumbnail", :src => @product.image_url}
  .col-md-5
    %h1= @product.title
    %blockquote= @product.description
    %h4
      Price:
      %span.label.label-primary= number_to_currency(@product.price, :unit => "$")
    %h4
      Avl Units:
      %span.label.label-primary= @product.units
    %a.btn.btn-primary.btn-sm{:href => "#"} Buy    
    .fb-like{"data-action" => "like", "data-href" => "http://www.iarts.co", "data-layout" => "button_count", "data-share" => "true", "data-show-faces" => "true"}
    %h5 Reputation: 97%
%br
.row{:style => "margin-left: 15px"}
  %legend Comments and questions
  %br
  .col-md-8.column
    .media
      %a.pull-left{:href => "#"}
        %img.media-object{:alt => "", :src => User.last.gravatar_url, :width => "64"}
      .media-body
        %h4.media-heading
          Question about 
          = @product.title
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
        .media
          %a.pull-left{:href => "#"}
            %img.media-object{:alt => "", :src => @product.user.gravatar_url, :width => "64"}/
          .media-body
            %h4.media-heading
              Hi 
              = current_user.full_name
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
    .media
      %a.pull-left{:href => "#"}
        %img.media-object{:alt => "", :src => "http://lorempixel.com/64/64/people", :width => "64"}
      .media-body
        %h4.media-heading
          Question about 
          = @product.title
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.
        .media
          %a.pull-left{:href => "#"}
            %img.media-object{:alt => "", :src => @product.user.gravatar_url, :width => "64"}/
          .media-body
            %h4.media-heading
              Hi Pedro
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis.

#fb-root
  - content_for :javascript do
    :javascript
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=179015472295336";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));

app/views/products/update.html.haml
%h1 Products#update
%p Find me in app/views/products/update.html.haml

app/views/welcome/index.html.haml
#carousel-750774.carousel.slide
  %ol.carousel-indicators
    %li.active{"data-slide-to" => "0", "data-target" => "#carousel-750774"}
    %li{"data-slide-to" => "1", "data-target" => "#carousel-750774"}
    %li{"data-slide-to" => "2", "data-target" => "#carousel-750774"}
    %li{"data-slide-to" => "3", "data-target" => "#carousel-750774"}
  .carousel-inner
    .item.active
      %img.carro{:alt => "", :src => "http://www.espaciolila.com/wasanyaka/wp-content/uploads/2013/07/cabecera02.jpg"}/
      .carousel-caption
        %h4
          On the hand with paintings!
        %p
          Handcrafting of the highest quality, painting on canvas, and on various materials carefully crafted by our artisans
    .item
      %img.carro{:alt => "", :src => "http://www.mediafire.com/convkey/dee1/wngf1m92n4nx8l9fg.jpg"}/
      .carousel-caption
        %h4
          Working the bamboo!...
        %p
          Cute vases and ornaments made in bamboo planted in our Colombian lands
    .item
      %img.carro{:alt => "", :src => "http://www.mediafire.com/convkey/5a7e/ai0n9qapd555h3zfg.jpg"}/
      .carousel-caption
        %h4
          Cane painted arrow! ..
        %p
          Handcrafts as centerpieces and decorations painted in arrow cane material, unique material and of the best queality in our country.
    .item
      %img.carro{:alt => "", :src => "http://www.mediafire.com/convkey/b985/exh8v6ihet7w0vvfg.jpg"}/
      .carousel-caption
        %h4
          Weaving weaving!...
        %p
          Cute hand woven bags in different techniques, different materials, from Coral thread to Wayuu thread, characteristic of this land.
  %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-750774"}
    %span.glyphicon.glyphicon-chevron-left
  %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-750774"}
    %span.glyphicon.glyphicon-chevron-right
.jumbotron
  %h1
    iArts.Co
  %p
    The platform for you to get the Colombian typical handicraft, where you will know about the different jobs of our craftsmen ... and even better: You will be able to get any of our creations!.
  %p
    %a.btn.btn-primary.btn-large{:href => "#"} Learn more
.row
  - @products.each do |product|
    .col-md-4
      .thumbnail
        %img{:alt => product.title, :src => product.image_url}/
        .caption
          %h3
            = product.title
          %p
            = raw(product.description.truncate(200, :omission => "...#{link_to "show more", '#'}"))
          %div
            = link_to "Show", product_path(product), :class => "btn btn-primary btn-sm"
            .fb-like{"data-action" => "like", "data-href" => "http://www.iarts.co", "data-layout" => "button_count", "data-share" => "true", "data-show-faces" => "true"}
#fb-root
  - content_for :javascript do
    :javascript
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=179015472295336";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));